version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - cd server
      - npm install
  build:
    commands:
      - npm run lint:fix
      - npm run test
      - npm run build
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - docker build -t $DOCKER_IMAGE_TAG .
  post_build:
    commands:
      - docker push $DOCKER_IMAGE_TAG
      - echo Build completed

artifacts:
  files:
    - dist/*
    - node_modules/*
    - package.json
  