version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run lint:fix
      - npm run test
      - npm run build
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - dist/*
    - node_modules/*
    - package.json
  